export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_FINISHED = "SEARCH_FINISHED";
export const SEARCH_TRACKS = "SEARCH_TRACKS";
export const SEARCH_ARTISTS = "SEARCH_ARTISTS";
export const SEARCH_ALBUMS = "SEARCH_ALBUMS";
export const SEARCH_ALL = "SEARCH_ALL";
export const SEARCH_ALL_LOADING = "SEARCH_ALL_LOADING";
export const SEARCH_ALL_FINISHED = "SEARCH_ALL_FINISHED";